version: "3.8"
 
services:
  app:
    container_name: singh_sajanpreet_coding_assignment11
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/src
    ports:
      - 3000:8083